### ISSUE TITLE
dynamoNodeDK not found!

### ISSUE THREAD

**Issue by puriahasaraki** [redinkinc/DynamoNDK#1]
Hi!
I'm new to this environment, but used a lot grasshopper development before.
The issue I have at the moment is that I'm trying to do the same thing but in the new dynamo, but for some reason I can't find the dynamoNodeDK in the src folder in dynamo-master folder.
Any suggestion where to find it?

**Comment by redinkinc** [comment]
hi @puriahasaraki,
which version of dynamo are you working with? I'm currently working on an update for Dynamo 0.7.x.
