### ISSUE TITLE
"You have to load the SampleLibraryZeroTouch.dll"

### ISSUE THREAD

**Issue by Fi-zz-mo** [redinkinc/DynamoNDK#2]
Is there a "how to" to let me know where I can find or how I can create this dll?

**Comment by redinkinc** [comment]
Hello @Fimo.
thanks for your remark. the dll is created when you successfully build your solution (VisualStudio project). It will add the SampleLibraryUI.dll and SampleLibraryZeroTouch.dll to your Dynamo 0.8/nodes folder. If the nodes are not displayed by default, you have to add them manually by selecting "add library", browse to C:\program files\dynamo 0.8\nodes and select the SampleLibraryZeroTouch.dll
If you have any further questions don't hesitate to ask.
Fabian

PS: I would recommend to update the DynamoNDK project to my latest commit.

**Comment by Fi-zz-mo** [comment]
Hello Fabian,

many thanks for your advice and the update - it now works great. However I get the impression the IRenderPackage may have lost some members (AddPointVertex, AddPointVertexColor, AddTriangleVertex ...)? The examples seem not to build, or have I overlooked anything here?

Best regards,
Fritz

**Comment by redinkinc** [comment]
Will have a look as soon as possible...

**Comment by redinkinc** [comment]
Hey Fritz,
sorry for the delay. I just run the project and everything seems to work fine. I added a screenshot from all the nodes that come with the project. Perhaps you can describe in more detail what is wrong in your project.
![unbenannt](https://cloud.githubusercontent.com/assets/3741716/7834009/b1e7dd46-046b-11e5-97c5-b0afce38376f.PNG)
regards, Fabian

**Comment by Fi-zz-mo** [comment]
Hi Fabian,

thanks for your reply. Please see attached two screenshots of my problem with building…
1. ```
   The problem
   ```
   
   [cid:image001.png@01D09879.88890410]
2. ```
   Trying to solve the problem…
   ```

[cid:image002.png@01D0987A.43B853D0]

So the method “AddPointVertex()” (resp the implementation of IRenderPackage) does not seem to exist any more and I do not know where to search for it…

Best regards,

Fritz

**Comment by redinkinc** [comment]
Sorry, you have to uplaod the screenshots in github and not via mail. otherwise I do not see them.

**Comment by Fi-zz-mo** [comment]
![screenshot1](https://cloud.githubusercontent.com/assets/12497475/7837001/c5e99992-0484-11e5-85be-74dc29849398.png)
![screenshot2](https://cloud.githubusercontent.com/assets/12497475/7837010/cf587282-0484-11e5-83d5-68e83e233b7d.png)

Sorry, didn't realize that...

**Comment by redinkinc** [comment]
which version of dynamo are you using? can you update to Dynamo 0.8.2 and try again? Seems like the older dll's miss some functionalities.

**Comment by Fi-zz-mo** [comment]
Ok, Dynamo 0.8.0 does not work, 0.8.2 does - thanks.

**Comment by redinkinc** [comment]
thanks for your hints.
